// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using zoo.Models;

namespace zoo.Migrations
{
    [DbContext(typeof(zooContext))]
    [Migration("20220205211302_V1")]
    partial class V1
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("zoo.Models.Lokacija", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .UseIdentityColumn();

                    b.Property<int>("Kapacitet")
                        .HasColumnType("int")
                        .HasColumnName("Kapacitet");

                    b.Property<int>("MaxKapacitet")
                        .HasColumnType("int")
                        .HasColumnName("MaxKapacitet");

                    b.Property<string>("Tip")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Tip");

                    b.Property<string>("Vrsta")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Vrsta");

                    b.Property<int?>("VrtID")
                        .HasColumnType("int");

                    b.Property<int>("X")
                        .HasColumnType("int")
                        .HasColumnName("X");

                    b.Property<int>("Y")
                        .HasColumnType("int")
                        .HasColumnName("Y");

                    b.HasKey("ID");

                    b.HasIndex("VrtID");

                    b.ToTable("Lokacija");
                });

            modelBuilder.Entity("zoo.Models.Vrt", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID")
                        .UseIdentityColumn();

                    b.Property<int>("Kapacitet")
                        .HasColumnType("int")
                        .HasColumnName("kapacitet");

                    b.Property<int>("M")
                        .HasColumnType("int")
                        .HasColumnName("m");

                    b.Property<int>("N")
                        .HasColumnType("int")
                        .HasColumnName("n");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Naziv");

                    b.HasKey("ID");

                    b.ToTable("Vrt");
                });

            modelBuilder.Entity("zoo.Models.Lokacija", b =>
                {
                    b.HasOne("zoo.Models.Vrt", "Vrt")
                        .WithMany("Lokacije")
                        .HasForeignKey("VrtID");

                    b.Navigation("Vrt");
                });

            modelBuilder.Entity("zoo.Models.Vrt", b =>
                {
                    b.Navigation("Lokacije");
                });
#pragma warning restore 612, 618
        }
    }
}
